name: ci-cd

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Install Gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run Go Tests
        run: go test -cover -v ./...

      - name: Run Gosec
        run: gosec ./..

  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: tests
    steps:
      # Ensure the following secrets are set in your repository:
      # DOCKERHUB_USERNAME - Your Docker Hub username
      # DOCKERHUB_TOKEN - Your Docker Hub access token (with write permissions)
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.5"

      - name: Build Binaries
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o ./bin/go-api-to-k8s .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: puppydog28/goapi:latest
          context: .
